version: '2'
services:
    emaxdata-app:
        image: emaxdata
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://emaxdata-mysql:3306/emaxdata?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    emaxdata-mysql:
        extends:
            file: mysql.yml
            service: emaxdata-mysql
